### ISSUE TITLE
Would a more modular approach benefit egraphs.py?

### ISSUE THREAD

**Issue by vitorCamarotto** [epoch-research/egraphs#1]
Hi,

I noticed that `egraphs.py` is a large file, with lots of different logic and responsability.

How would it feel for a more modular approach, in order to favor maintainability and readability.

Here's what I imagined:
`egraph_style_config.py` -> File that will contain all styling (colors, fonts, etc)
`egraph_utils.py` -> File for general utilities like `px_to_pt`, `in_to_px`, `px_to_x_fraction`, etc.
`egraph_theme.py` -> File for matplotlib's theme management

Finally, making `egraph.py` more into a handler and general actioner.

**Comment by vitorCamarotto** [comment]
Also, sorry about anything in advance, but as there was no contribution page, I just shared with my personal opinion.

**Comment by eirol** [comment]
Thanks for the suggestions!

This is just a temporary repository that will be replaced hopefully soon. So, refactoring it is not worth it. I appreciate your suggestions, though!
